mcc: '208'          # Mobile Country Code value
mnc: '95'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 0xa000              # Tracking Area Code

linkIp: 127.0.0.1   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 192.168.70.140  # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 192.168.71.140    # gNB's local IP address for N3 Interface (Usually same with local IP)
gtpuConfig:
  srcMac: '00:22:48:ce:99:e4'
  srcIp: '192.168.71.140'
  dstMac: '00:22:48:cf:71:f9'
  dstIp: '192.168.71.134'
  interface: 'eth0'

# List of AMF address information
amfConfigs:
  - address: 192.168.70.132
    port: 38412


fgcMac: '60:45:bd:43:3a:17' # Mac address of the Machine with the core network

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 222
    sd: 123

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
